name: Deploy
run-name: Deploy to RPI
on:
  push:
    branches:
      - main
jobs:
    Deploy:
        runs-on: self-hosted
        steps:
          - run: ls ~/cubus
          - run: cd ~/cubus && git pull && npm run build
          - run: pwd
