name: Deploy
run-name: Deploy project
on:
  push:
    branches:
      - main
jobs:
    Deploy:
        runs-on: self-hosted
        defaults:
          run:
            working-directory: ../../../../cubus
        steps:
          - name: Clone Codebase
            run: git pull
          - name: Install Dependencies
            run: npm i && composer i
          - name: Compile
            run: npm run build
